version: '3.8'
services:

  keycloak:
    build: ./keycloak/.
    ports:
      - 8080:8080
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    command: "start-dev --import-realm"

  mongo:
    image: davybello/mongo-replica-set:5.0.12
    ports:
      - 27017:27017
      - 27018:27018
      - 27019:27019

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    hostname: kafka
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
      - 5555:5555
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_ADVERTISED_HOST_NAME: localhost
      
  akhq:
    image: tchiotludo/akhq
    depends_on:
      - kafka
    ports:
      - 19000:8080
    environment:
      AKHQ_CONFIGURATION: |
        akhq:
          connections:
            docker-kafka-server:
              properties:
                bootstrap.servers: "kafka:29092"

  # back-ts:
  #   build: ./back-typescript/.
  #   ports:
  #     - 3001:3001
  #   depends_on:
  #     - kafka
  #   environment:
  #     PORT: 3001
  #     MONGO: mongo:27017
  #     KAFKA_BROKER: kafka:29092
  #     KEYCLOAK: keycloak:8080
          